CREATE TABLE BRANDS (
    ID INT PRIMARY KEY,
    BRAND VARCHAR(255) NOT NULL
);

CREATE TABLE PRICES (
    ID BIGINT PRIMARY KEY,
    BRAND_ID VARCHAR(255),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    PRIORITY INT,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(3),

    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);

CREATE SEQUENCE prices_seq START WITH 1 INCREMENT BY 1;
