openapi: 3.0.1
info:
  title: Price by productId, brandId and date
  description: Endpoint that gets the price of a product by productId, brandId and date
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: local
paths:
  /price:
    get:
      tags:
        - price
      operationId: getPrice
      parameters:
        - name: filter
          in: query
          required: true
          schema:
            "$ref": '#/components/schemas/PriceFilterDTO'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/PriceDTO'
        '404':
          description: Not Found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    PriceFilterDTO:
      type: object
      required:
        - productId
        - brandId
        - date
      properties:
        productId:
          type: string
          description: Product id
          example: 35455
        brandId:
          type: string
          description: Brand id
          example: 1
        date:
          type: string
          description: Date
          format: date-localdatetime
          example: 2020-06-14T10:00:00Z
    PriceDTO:
      type: object
      properties:
        productId:
          type: string
          description: Product id
          example: 35455
        brandId:
          type: string
          description: Brand id
          example: 1
        priceList:
          type: string
          description: Fare id
          example: 1
        startDate:
          type: string
          description: Price start date
          format: date-localdatetime
          example: 2018-03-20T09:12:28Z
        endDate:
          type: string
          description: Price end date
          format: date-localdatetime
          example: 2018-03-20T09:12:28Z
        price:
          type: number
          description: Price
          format: decimal
          example: 99.95
        currency:
          type: string
          description: Currency ISO-4217
          format: iso-4217
          example: EUR
    ErrorMessage:
      type: object
      properties:
        error:
          type: string
